version: "3.7"

services:
  postgres:
    image: postgres
    container_name: database
    restart: always 
    ports:
      - 15432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bank-database
    volumes:
      - ./pgdata:/data/postgres

  api:
    build: ./bank-test-back
    container_name: bank-api
    command: sh -c "yarn && yarn dev"
    ports:
      - 3333:3333
    volumes: 
      - ./bank-test-back:/app
    depends_on: 
      - postgres

  client:
    build: ./bank-test-client
    container_name: bank-client
    command: sh -c "yarn && yarn start"
    ports:
      - 8080:3000
    volumes: 
      - ./bank-test-client:/app
    depends_on: 
      - api

volumes:
  pgdata:
    driver: local
      